platform :ios, '7.0'
inhibit_all_warnings!
pod 'AFNetworking'
pod 'SDWebImage'
pod 'RESideMenu'
pod 'Mantle'
pod 'M13ProgressSuite'
pod 'SVPullToRefresh'
pod 'Facebook-iOS-SDK'
pod 'JPSThumbnailAnnotation'
pod 'EAIntroView'
pod 'CCHMapClusterController'
pod 'MWPhotoBrowser'
pod 'SVSegmentedControl'
pod 'MPGNotification'
pod 'MCSwipeTableViewCell'
pod 'JSQMessagesViewController'
pod 'JGActionSheet'